### ISSUE TITLE
scenario.DependencyResolver.Resolve() in Decorator creates a new resource instead of getting current one

### ISSUE THREAD

**Issue by dstj** [LightBDD/LightBDD#186]
#### Description
_Note: I am unsure as to if this is a bug or just something I do not understand about LightBDD DI Container, so I also created a [StackOverflow post](https://stackoverflow.com/q/56369889/918244). But seeing as though the tag `lightbdd` didn't exist on SO, I don't think I'll get a reply there._

I'm using LightBDD to run Selenium tests and I'm trying to automatically take a screenshot whenever a scenario fails. I wrote a [class-level Decorator](https://github.com/LightBDD/LightBDD/wiki/Extending-Test-Behavior#class-level) to do this. But, getting the ChromeDriver from the DI container in the Decorator retrieves a **new** instance of the ChromeDriver from the `ResourcePool` instead of retrieving the current ChromeDriver used by the scenario.

That creates a new Chrome window, on a blank page, so the screenshot is blank instead of the state of things when the error occured. **Shouldn't it get the one used in the scenario?**

I'm registering the ChromeDriver as in the [provided example](https://github.com/LightBDD/LightBDD/wiki/DI-Containers#resourcepool-example-usage):

```c#
config.RegisterInstance(
        new ResourcePool<ChromeDriver>(CreateDriver),
        new RegistrationOptions());
```

and my decorator is getting the ChromeDriver like this:

```
try {
	await scenarioInvocation();
}
catch (Exception ex) {
	var driverHandle = scenario.DependencyResolver.Resolve(typeof(ResourceHandle<ChromeDriver>));
        var driver = await ((ResourceHandle<ChromeDriver>) driverHandle).ObtainAsync();
        ...
}
```

After the `ObtainAsync()` call, the debugger clearly shows that two instances are in the DI Container now:

[![scenario.DependencyResolver debugger][1]][1]

  [1]: https://i.stack.imgur.com/5RWth.png

**Comment by Suremaker** [comment]
Hello @dstj 

You are seeing this problem because [the default DI container](https://github.com/LightBDD/LightBDD/wiki/DI-Containers#default-di-container) resolves the type by making a new instance every time when you ask. That is why your test and your decorator gets different instances.

To make it working the way you want, you will have to use more advance DI (like Autofac) and configure the `ResourceHandle<ChromeDriver>` to have **scope** lifetime. It would mean that while each scenario will get own copy of the handle, the scenario code and your decorator code will get a shared one.

Here is the code for the container configuration:

```c#
    public class ConfiguredLightBddScopeAttribute : LightBddScopeAttribute
    {
        protected override void OnConfigure(LightBddConfiguration configuration)
        {
            configuration.DependencyContainerConfiguration()
                .UseAutofac(ConfigureContainer());
        }

        private ContainerBuilder ConfigureContainer()
        {
            var builder = new ContainerBuilder();
            builder.RegisterInstance(new ResourcePool<ChromeDriver>(CreateDriver));
            builder.RegisterType<ResourceHandle<ChromeDriver>>().InstancePerLifetimeScope(); // <-- this make the difference
            return builder;
        }

        private ChromeDriver CreateDriver()
        {
            var driver = new ChromeDriver();
            driver.Manage().Timeouts().ImplicitWait = TimeSpan.FromMilliseconds(0);
            return driver;
        }
    }
```

This would require adding `LightBDD.Autofac` package to the project.

... also I would suggest to rethrow the exception from your TakeScreenshotOnErrorAttribute so that the exception would flow properly and fail the scenario:

```c#
public async Task ExecuteAsync(IScenario scenario, Func<Task> scenarioInvocation)
{
	try
	{
		await scenarioInvocation();
	}
	catch (Exception ex)
	{
		await TakeScreenshot(scenario);
		throw; // <-- here
	}
}
```

Finally I have attached a working sample here: 
[LightBDDTests1.zip](https://github.com/LightBDD/LightBDD/files/3241856/LightBDDTests1.zip)

I hope that helps! :)

**Comment by dstj** [comment]
Thanks! I guess I assumed all `ResourcePool<>` resources in the default DI container were scoped by scenario by default. It all makes sense now. Thanks a lot!
