### ISSUE TITLE
Improve Dependency injection scopes

### ISSUE THREAD

**Issue by ipatalas** [LightBDD/LightBDD#219]
Hi,

just trying to get one thing done and having some difficulties.
According to [this](https://github.com/LightBDD/LightBDD/wiki/DI-Containers#container-scopes) each scenario has it's own scope but additional scopes get created for composite steps.
How do I properly share a dependency between my top-level steps and steps which are in a composite step and use their own context?
Top-level steps are using `StepExecution.Current.GetScenarioDependencyResolver().Resolve<T>()` to inject a dependency and context uses constructor injection. Unfortunately I get two different instances while I'd like to share session state throughout entire scenario.
The docs say __Finally, container scopes are hierarchical, which means that they are aware of their parent and depending on configuration can use dependencies specified in higher scopes for injections.__
Can it be achieved using default DI container or only by applying a custom one which can handle scopes other than transient or singleton?

Maybe there is also a different way to share state between contexts for instance? I haven't found a proper example for that. 
I can't use neither of the methods described [here](https://github.com/LightBDD/LightBDD/wiki/Scenario-State-Management#scenario-state-management) because they only solve state sharing inside one "scope" (either context or a fixture class).

I come more from SpecFlow world and there was something like [`ScenarioContext`](https://docs.specflow.org/projects/specflow/en/latest/Bindings/ScenarioContext.html#migrating-from-scenariocontext-current) which is basically a bag for anything that you want to share between steps no matter where the steps are defined.
I can't find a good way to achieve something similar in **LightBDD**.
Well.. I can imagine reimplementing a concept of `ScenarioContext` using **AutoFac** but don't want to reinvent the wheel. Maybe it can be done without 3rd party DI?

**Comment by Suremaker** [comment]
Hey @ipatalas ,

Let me first refer to your questions:

> Can it be achieved using default DI container or only by applying a custom one which can handle scopes other than transient or singleton?

The default DI is a very simple one, designed to do the basic stuff - allow you to instantiate types with an automatic resolution for constructor dependencies and allow to register some of those dependencies to be shared across all tests (singletons).
For all more advanced scenarios, one of the industry DI has to be used (Autofac or anything which is compatible with IServiceProvider).

> The docs say Finally, container scopes are hierarchical, which means that they are aware of their parent and depending on configuration can use dependencies specified in higher scopes for injections.

This is true. When a scenario starts, a new container scope is created allowing to instantiate and dispose resources that are needed for the scenario lifetime. The same happens when a composite step is executed. The new scopes are aware of their parents though.
For Autofac or Microsoft DI (for example) all types which are transient or with scoped lifetime will be created within this new scope and disposed at the scope exit, however, the singletons will be resolved from the root scope.

Now there are the following challenges that might by not obvious:
* both, Microsoft DI (`services.AddScoped()`) and Autofac (`builder.RegisterType<...>().InstancePerLifetimeScope()`) does not share the scoped instances with the nested scopes. It means that even if you use scoped lifetime, the instance will be shared let's say within scenario steps, but you will still get a new instance for the composite step (inner scope).
* the Autofac has an option for supporting instances with inner scopes i.e. `builder.RegisterType<Worker>().InstancePerMatchingLifetimeScope("myrequest")` ([link](https://autofaccn.readthedocs.io/en/latest/lifetime/instance-scope.html#instance-per-matching-lifetime-scope)) but LightBDD does not support naming the scopes at the moment,

> I come more from SpecFlow world and there was something like ScenarioContext which is basically a bag for anything that you want to share between steps no matter where the steps are defined.

LightBDD does not offer it out of the box, as working with an unstructured bag of anything makes maintenance of the tests harder as you lose control over who set the state when and why. The other challenge is with controlling resource lifetime, i.e. if you want to dispose the resources and when. The scenario/step context is designed to work for it instead.

However, if you prefer to go this way, I can provide you an example how to achieve it!

-----

Let's take a look at what we can do with LightBDD. The combination of DI, scenario/step contexts, and a few extensibility points could help us.

### Resources shared between all features and scenarios

You can use here DI (including default one) and register instances as singletons. They will be wired in automatically on context instantiation (`Runner.WithContext<>` or `CompositeStep.DefineNew().WithContext<>`) or by `StepExecution.Current.GetScenarioDependencyResolver().Resolve<T>()`.

For manual control of the singletons or specific actions that you would like to run once for all tests, you can use `OnSetUp() / OnTearDown()` methods of [LightBDDConfiguration](https://github.com/LightBDD/LightBDD/wiki/LightBDD-Configuration).
I often initialize here the global repositories or initialize and dispose the test server for WebApis.

### Resources shared between steps in the scenario

Following [wiki](https://github.com/LightBDD/LightBDD/wiki/Scenario-State-Management#scenario-state-management) the scenario state is managed by feature fixture members or context members i.e. fields of your class that contains the step definition.

To share those resources with composite steps you can do it in the following ways:

Let's assume you have a feature:
```c#
public class My_feature : FeatureFixture
{
    [Scenario]
    public void Scenario_1()
    {
        Runner
            .WithContext<FeatureContext>()
            .RunScenario(
                x => x.Set_some_scenario_state("My user ID 1"),
                x => x.Show_state(),
                x => x.Manual_composite(),
                x => x.Manual_composite(),
                x => x.Scenario_resolved_composite(),
                x => x.Scenario_resolved_composite());
    }

    [Scenario]
    public void Scenario_2()
    {
        Runner
            .WithContext<FeatureContext>()
            .RunScenario(
                x => x.Set_some_scenario_state("My user ID 2"),
                x => x.Show_state(),
                x => x.Manual_composite(),
                x => x.Manual_composite(),
                x => x.Scenario_resolved_composite(),
                x => x.Scenario_resolved_composite(),
                x => x.Automatically_resolved_composite(),
                x => x.Automatically_resolved_composite());
    }
}
```
... and feature context:

```c#
class FeatureContext
{
    private readonly DependencyA _depA; //DI resolved
    private readonly DependencyB _depB; //DI resolved
    private ScenarioCustomState _scenarioState; //Custom state

    public FeatureContext(DependencyA depA, DependencyB depB)
    {
        _depA = depA;
        _depB = depB;
    }
}
```

#### Create step context manually
```c#
class FeatureContext
{
    //...
    public CompositeStep Manual_composite()
    {
        return CompositeStep.DefineNew()
            .WithContext(() => new ManualCompositeContext(_depA, _depB, _scenarioState)) //manually created
            .AddSteps(x => x.Show_state())
            .Build();
    }
}
```
In this approach `ManualCompositeContext` is not resolved from DI and all it's dependenices have to be resolved manually, but you can pass here either the state from your scenario fields or previously resolved from DI.
If the `ManualCompositeContext` is disposable, it will be still disposed after the composite step finish execution.

#### Dependencies resolved from scenario context

```c#
class FeatureContext
{
    //...
    public CompositeStep Scenario_resolved_composite()
    {
        return CompositeStep.DefineNew()
            .WithContext(() => StepExecution.Current.GetScenarioDependencyResolver()
                .Resolve<ResolvedCompositeContext>() //composite context resolved from DI, scenario scope
                .WithState(_scenarioState)) //and customised with scenario state
            .AddSteps(x => x.Show_state())
            .Build();
    }
}
```

In this approach the `ResolvedCompositeContext` is created using ScenarioDependencyResolver to resolve all standard dependencies, while the scenario specific state is passed separately with method `WithState()`.

The step context looks as follows:
```c#
class ResolvedCompositeContext
{
    private readonly DependencyA _depA;
    private readonly DependencyB _depB;
    private ScenarioCustomState _state;

    public ResolvedCompositeContext(DependencyA depA, DependencyB depB)
    {
        _depA = depA;
        _depB = depB;
    }

    public ResolvedCompositeContext WithState(ScenarioCustomState state)
    {
        _state = state;
        return this;
    }
}
```

Again, if the `ResolvedCompositeContext` is disposable, it will be still disposed after the composite step finish execution, however anything that was resolved using `StepExecution.Current.GetScenarioDependencyResolver()` will be disposed after the whole scenario.

#### Dependencies resolved from step context, scenario data passed in business flow

```c#
class FeatureContext
{
    //...
    public CompositeStep Automatically_resolved_composite()
    {
        return CompositeStep.DefineNew()
            .WithContext<ResolvedCompositeContext>() //composite context resolved from DI, composite step scope
            .AddSteps(
                x => x.Given_scenario_state(_scenarioState), //scenario state passed as part of business flow
                x => x.Show_state())
            .Build();
    }
}
```

Here, the `ResolvedCompositeContext` is created using composite step scope  - singletons are shared with scenario, but all other dependencies are created as new ones. Any new instances which are disposable, will be disposed after composite step finish.

The scenario state is passed via business flow (`Given_scenario_state`). It may be valid approach if you want to explicitly say that you work on the specific user, order or some other business concept.

### Outcome

#### Default DI

If I configure the default DI and make DependencyA a singleton but DependencyB not:
```c#
internal class ConfiguredLightBddScopeAttribute : LightBddScopeAttribute
{
    protected override void OnConfigure(LightBddConfiguration configuration)
    {
        configuration.DependencyContainerConfiguration()
            .UseDefaultContainer(Configure);
    }

    private void Configure(ContainerConfigurator cfg)
    {
        cfg.RegisterInstance(new DependencyA(), new RegistrationOptions()); //singleton
    }

    protected override void OnSetUp()
    {
        // code executed before any scenarios
    }

    protected override void OnTearDown()
    {
        // code executed after all scenarios
    }
}
```

... this will be my outcome:
![image](https://user-images.githubusercontent.com/1894621/105577835-cf91e780-5d73-11eb-8a60-d2d3ecf3a311.png)

The DependencyA is always the same instance.
The DependencyB is different between scenarios however within the scenario it is:
* the same in manual steps,
* different in resolved steps, no matter how we resolve them.

#### MS DI

Now, if we use more advanced DI like Microsoft one:
```c#
protected override void OnConfigure(LightBddConfiguration configuration)
{
    configuration.DependencyContainerConfiguration()
        .UseContainer(ConfigureMsDI(), true);
    //.UseDefaultContainer(ConfigureDefaultDI);
}

private ServiceProvider ConfigureMsDI()
{
    var services = new ServiceCollection();
    services.AddSingleton<DependencyA>();
    services.AddScoped<DependencyB>();
    services.AddTransient<FeatureContext>();
    services.AddTransient<ResolvedCompositeContext>();
    return services.BuildServiceProvider();
}
```

... this will be my outcome:
![image](https://user-images.githubusercontent.com/1894621/105578024-3fed3880-5d75-11eb-9acb-ca4f906bc5ee.png)

The DependencyA is always the same instance.
The DependencyB is different between scenarios however within the scenario it is:
* the same in manual steps,
* the same when resolved with `StepExecution.Current.GetScenarioDependencyResolver()`
* different if resolved using composite step scope

I hope it answers your question and will give you enough flexibility to achieve what you need!
I will appreciate for the feedback to see what area around DI could be done better or easier to use!

I have also attached a full example here:
[LightBDDWithDI.zip](https://github.com/LightBDD/LightBDD/files/5860193/LightBDDWithDI.zip)

**Comment by Suremaker** [comment]
I have also update the wiki to provide more details about sharing state with composite steps: https://github.com/LightBDD/LightBDD/wiki/Scenario-State-Management#sharing-state-with-composite-steps

**Comment by ipatalas** [comment]
Wow, thanks! This is probably the most comprehensive answer I have ever got on GitHub :)
This helps a lot. However it still feels like I need to struggle with workarounds to get relatively easy thing done.

Let me briefly explain what I'm trying to do. Maybe there is a better way to do that which I can't see yet.
I'm trying to write an integration test for our API which simply calls different APIs to cover a business flow. There will be many tests like that - we're just starting.
The thing is vast majority of the APIs are authenticated so almost always the first step is to authenticate the user and get a JWT token which then needs to be used in all subsequent calls. This is so far the only thing for which I needed to have a scenario-scoped state.
There is an API client for our API which simply holds that token for its lifetime. I used that ApiClient as a dependency which is being injected in different places in a scenario. 
At the beginning we don't need context or composite steps but I'm trying to be one step ahead as the tests will grow quickly. 
I've done everything in a single FeatureFixture and it works well because the ApiClient is always the same instance in a scenario.
Then I prepared a quick example with extra context and a composite step and figured out I'm getting different instances.
I'd like to have a nice DX (developer experience) here so ideally we just make the first call to authenticate the user and then just call other endpoints which automatically use the token retrieved in the first step. Passing the token explicitly each time to pretty much every single step would be a massive overkill and readability killer.

I do see a different workaround now - I could register that as a singleton and then use `[SetUp]`/`[TearDown]` handlers (NUnit integration) to clean the state but this will not be very straightforward and doesn't feel like a clean solution for such a simple problem. This is probably quite common scenario in integration testing so a clean solution for that would be really helpful.
All the other states are rather local so they will probably live inside one context only so they are not problematic at all.

From all the options you proposed above I like the solution with `StepExecution.Current.GetScenarioDependencyResolver()` the most. It's almost perfect. I can easily write an extension method to encapsulate that into a single short method to be able to do sth like:
```cs
public CompositeStep Scenario_resolved_composite()
{
  return CompositeStep.DefineNew()
    .WithContextScenarioScope<ResolvedCompositeContext>()
    .AddSteps(x => x.Show_state())
    .Build();
}
```
If you see a better way to do that please share your thoughts.

**Comment by Suremaker** [comment]
Hey @ipatalas ,

Thanks for providing more context. Hmm, so it looks like you like to get Jwt token and set it for api client. It definitely looks like technical detail that could be hidden from the business flow.

How about using the [scenario decorator](https://github.com/LightBDD/LightBDD/wiki/Extending-Test-Behavior) then?
You can apply it on all scenarios (global registration) or give developers an option to use when needed (attribute version).
It will run for each scenario and you will be able to get your api client instance (via DI resolver) and configure it with jwt token, and even do the custom cleanup after execution.
It should be better than nunit setup/teardown as it will be abstracted away from the test classes, giving you more flexibility.

Let me know if that will help solving your problem!

> Wow, thanks! This is probably the most comprehensive answer I have ever got on GitHub :)

You are welcome, I hope it will help ;)

**Comment by ipatalas** [comment]
> How about using the [scenario decorator](https://github.com/LightBDD/LightBDD/wiki/Extending-Test-Behavior) then?
> You can apply it on all scenarios (global registration) or give developers an option to use when needed (attribute version).
> It will run for each scenario and you will be able to get your api client instance (via DI resolver) and configure it with jwt token, and even do the custom cleanup after execution.

In general it looks good. We could have for instance `AnonymousUserAttribute` or `TestUserAttribute` depending on which one of these is needed for a test. However I think it still isn't a final solution. I could use DI resolver inside the decorator which will correctly return me the ApiClient of Scenario scope. Then I need to be able to inject the same ApiClient instance in test steps (regardless of whether this will be a top-level step or one hidden in a deeper context) so we're back to my original problem which still needs to be solved somehow (in one of the ways you have presented in your original answer) :)

In case you want to play with that specific case here is a sample based on the one you have prepared. I have just deleted most of unnecessary stuff. The last step fails because it gets a different instance - the first one using scenario resolved composite works just fine and this looks like the best solution so far.

[LightBDDWithDI.zip](https://github.com/LightBDD/LightBDD/files/5862990/LightBDDWithDI.zip)

**Comment by Suremaker** [comment]
Hey @ipatalas ,

I could take a look at it just now. If you have not resolved it yet, I would suggest one of 2 options.

Option 1 is to use MS DI and always using `StepExecution.Current.GetScenarioDependencyResolver()` to resolve composite context - this way you will always get the same ApiClient instance within the scenario.

Option 2 is to not use DI for ApiClient but rather manage it purely with `ScenarioDecorator` and `AsyncLocal<T>` which will allow different instances to be available for scenarios while allowing to execute them in parallel.

I will focus here on this option.

#### ApiClientContext
```c#
public class ApiClientContext : IScenarioDecorator
{
    private static readonly AsyncLocal<ApiClient> _asyncLocal = new AsyncLocal<ApiClient>();

    public static ApiClient Client => _asyncLocal.Value ?? throw new InvalidOperationException("Client not initialized");

    async Task IScenarioDecorator.ExecuteAsync(IScenario scenario, Func<Task> scenarioInvocation)
    {
        using (var client = new ApiClient())
        {
            try
            {
                _asyncLocal.Value = client;
                await scenarioInvocation();
            }
            finally
            {
                _asyncLocal.Value = null;
            }
        }
    }
}
```
It is a scenario decorator that will create a new ApiClient for each executed scenario and make it available to use via `ApiClientContext .Client` property, where the instance will be available only for this scenario and only for the lifetime of it (it is disposed after).
The [AsyncLocal<T>](https://docs.microsoft.com/en-us/dotnet/api/system.threading.asynclocal-1?view=net-5.0) allows having different values per asynchronous control flow, so executing multiple tests in parallel.

The decorator is installed then for all scenarios:
```c#
internal class ConfiguredLightBddScopeAttribute : LightBddScopeAttribute
{
    protected override void OnConfigure(LightBddConfiguration configuration)
    {
        //...
        configuration.ExecutionExtensionsConfiguration()
            .EnableScenarioDecorator<ApiClientContext>();
    }

    //...
}
```

#### Attributes to control authentication

```c#
public class AnonymousAuthentication : Attribute, IScenarioDecoratorAttribute
{
    public async Task ExecuteAsync(IScenario scenario, Func<Task> scenarioInvocation)
    {
        ApiClientContext.Client.AuthenticateUser("anonymous");
        await scenarioInvocation();
    }

    public int Order { get; }
}

public class TestUserAuthentication : Attribute, IScenarioDecoratorAttribute
{
    public async Task ExecuteAsync(IScenario scenario, Func<Task> scenarioInvocation)
    {
        ApiClientContext.Client.AuthenticateUser("testUser");
        await scenarioInvocation();
    }

    public int Order { get; }
}
```

Those attributes are another scenario decorators that will be run after `ApiClientContext`, so they will have access to `ApiClientContext.Client` allowing to authenticate user you like to have.

### Context files (Api access)

```c#
class FeatureContext
{
    private ApiClient ApiClient => ApiClientContext.Client;

    public void Business_Call_1()
    {
        ApiClient.Business_Call_1();
    }

    //...
}

class ResolvedCompositeContext
{
    private ApiClient ApiClient => ApiClientContext.Client;

    public void Business_Call_2()
    {
        ApiClient.Business_Call_2();
    }
}
```

The context classes do not use DI but `ApiClientContext.Client` to access the API client.

**NOTE** : you can only use this property from the step methods, but not in the constructors.

### Scenarios

```c#
public class My_feature : FeatureFixture
{
    [Scenario]
    [TestUserAuthentication]
    public void Scenario_1()
    {
        Runner
            .WithContext<FeatureContext>()
            .RunScenario(
                x => x.Business_Call_1(),
                x => x.Scenario_resolved_composite(),
                x => x.Automatically_resolved_composite());
    }

    [Scenario]
    [AnonymousAuthentication]
    public void Scenario_2()
    {
        Runner
            .WithContext<FeatureContext>()
            .RunScenario(
                x => x.Business_Call_1(),
                x => x.Scenario_resolved_composite(),
                x => x.Automatically_resolved_composite());
    }
}
```

Outcome:
```
SCENARIO: Scenario 1
  STEP 1/3: Business Call 1...
  STEP 1/3: /* ApiClient_ApiClient_2: testUser */
  STEP 1/3: /* Business_Call_1 succeeded */
  STEP 1/3: Business Call 1 (Passed after <1ms)
  STEP 2/3: Scenario resolved composite...
  STEP 2.1/2.1: Business Call 2...
  STEP 2.1/2.1: /* ApiClient_ApiClient_2: testUser */
  STEP 2.1/2.1: /* Business_Call_2 succeeded */
  STEP 2.1/2.1: Business Call 2 (Passed after <1ms)
  STEP 2/3: Scenario resolved composite (Passed after <1ms)
  STEP 3/3: Automatically resolved composite...
  STEP 3.1/3.1: Business Call 2...
  STEP 3.1/3.1: /* ApiClient_ApiClient_2: testUser */
  STEP 3.1/3.1: /* Business_Call_2 succeeded */
  STEP 3.1/3.1: Business Call 2 (Passed after <1ms)
  STEP 3/3: Automatically resolved composite (Passed after <1ms)
  SCENARIO RESULT: Passed after 2ms

SCENARIO: Scenario 2
  STEP 1/3: Business Call 1...
  STEP 1/3: /* ApiClient_ApiClient_1: anonymous */
  STEP 1/3: /* Business_Call_1 succeeded */
  STEP 1/3: Business Call 1 (Passed after 7ms)
  STEP 2/3: Scenario resolved composite...
  STEP 2.1/2.1: Business Call 2...
  STEP 2.1/2.1: /* ApiClient_ApiClient_1: anonymous */
  STEP 2.1/2.1: /* Business_Call_2 succeeded */
  STEP 2.1/2.1: Business Call 2 (Passed after <1ms)
  STEP 2/3: Scenario resolved composite (Passed after 5ms)
  STEP 3/3: Automatically resolved composite...
  STEP 3.1/3.1: Business Call 2...
  STEP 3.1/3.1: /* ApiClient_ApiClient_1: anonymous */
  STEP 3.1/3.1: /* Business_Call_2 succeeded */
  STEP 3.1/3.1: Business Call 2 (Passed after <1ms)
  STEP 3/3: Automatically resolved composite (Passed after 1ms)
  SCENARIO RESULT: Passed after 35ms
```

[LightBDDWithDI.zip](https://github.com/LightBDD/LightBDD/files/5876151/LightBDDWithDI.zip)

I have attached the example solution.

Personally, I would lean towards Option 1 as it will be more obvious what is going on. In that option, you can still use the attribute-based authentication as `IScenario scenario` gives you access to the resolver, i.e:
```c#
public class AnonymousAuthentication : Attribute, IScenarioDecoratorAttribute
{
    public async Task ExecuteAsync(IScenario scenario, Func<Task> scenarioInvocation)
    {
        scenario.DependencyResolver.Resolve<ApiClient>().AuthenticateUser("anonymous");
        await scenarioInvocation();
    }

    public int Order { get; }
}
```

**Comment by ipatalas** [comment]
Hi, that's great. I'll take a look on that.

Meanwhile I have found an undocumented (?) feature: [ScenarioExecutionContext](https://github.com/LightBDD/LightBDD/blob/master/src/LightBDD.Core/ExecutionContext/ScenarioExecutionContext.cs).
It uses `AsyncLocal` under the hood and seem to do what I wanted. 
It doesn't exactly work as I expected - I mean I understood scenario scope in a slightly different way. I thought any code executed inside a scenario will have scenario execution context already in place but it seems like it works differently. 
Scenario itself just builds the test to be executed and then `RunAsync()` executes it so this context is only available in steps but not in constructor of a context built with `.WithContext<T>()`. That's ok though. I just used lazy initialization for ApiClient and it works just fine.
Checked few tests run in parallel and they all get an isolated ApiClient instance which is good.

**Comment by Suremaker** [comment]
Hey, the `ScenarioExecutionContext` is the core concept used to hold the state for scenarios and the steps.
It is not officially documented on wiki as this type is placed in LightBDD.Core namespace and used for LightBDD engine.
You can use it if you like, but unlike the example, I have shown above the `ScenarioExecutionContext` does not handle disposables and you may get into trouble if you'd need to clean up the resources after the scenario/step.

> It doesn't exactly work as I expected - I mean I understood scenario scope in a slightly different way. I thought any code executed inside a scenario will have scenario execution context already in place but it seems like it works differently.
Scenario itself just builds the test to be executed and then RunAsync() executes it so this context is only available in steps but not in constructor of a context built with .WithContext<T>(). That's ok though. I just used lazy initialization for ApiClient and it works just fine.

It is correct, the Scenario method or composite step methods are more like prescriptions of what needs to be done. The steps themselves are executed when you call `Run()` or `RunAsync()`. This design gives LightBDD the ability to include all the steps on the report (even those that did not execute yet):

![image](https://user-images.githubusercontent.com/1894621/106067644-0579f780-60f7-11eb-9f51-9d94caa96a26.png)

... but the execution contexts or some functionalities like `StepExecution.Current` are only available when you run the scenario and not in Fixture constructors or Setup/TearDown/Dispose methods.

---

Finally, I am looking at the free time if I could extend the basic container to allow registering scenario scoped dependencies - I will keep you posted on the progress.

**Comment by ipatalas** [comment]
> Hey, the `ScenarioExecutionContext` is the core concept used to hold the state for scenarios and the steps.
> It is not officially documented on wiki as this type is placed in LightBDD.Core namespace and used for LightBDD engine.
> You can use it if you like, but unlike the example, I have shown above the `ScenarioExecutionContext` does not handle disposables and you may get into trouble if you'd need to clean up the resources after the scenario/step.

You're right. I would need to take care of disposing the resources - I could (?) use Scenario decorator for that but then the solution will be a mix of two different things which is not the best option. I'd rather keep it in one place so perhaps one of the two options above will be better.

> Finally, I am looking at the free time if I could extend the basic container to allow registering scenario scoped dependencies - I will keep you posted on the progress.

That would be really great. I think this is quite common case to have in integration tests so that would be really useful to have it working "natively".

**Comment by Suremaker** [comment]
Hey @ipatalas ,

I hope you have found an implementation making your life easier by this time.
In the meantime, I have made a PR with a set of the improvements around the default dependency container, the Autofac as well as Microsoft DI - the details are in the PR linked above.

In the next few days I will merge it and release the new version of LightBDD.
Please let me know if the changes will be helpful for you.

**Comment by Suremaker** [comment]
Hey @ipatalas.
I have released the LightBDD 3.3.0 with improved management of the Dependency Injection scopes.

More information can be found on:
* [What Is New](https://github.com/LightBDD/LightBDD/wiki/What-Is-New#lightbdd-330)
* [DI Containers](https://github.com/LightBDD/LightBDD/wiki/DI-Containers)
* [Scenario State Management](https://github.com/LightBDD/LightBDD/wiki/Scenario-State-Management#sharing-state-with-composite-steps) how-to page

**Comment by ipatalas** [comment]
Hi,

I didn't have time to look at this before but I have read the release notes now and it looks really great!
Good job! 💪🏻 
I like the way you handled backward compatibility so that it silently falls back to transient scope if there is no explicit registration telling otherwise. That's what I have been looking forward to when I started reading about the changes.
That makes it easy to slowly progress towards scenario scoped registrations one by one without having to configure everything explicitly.
I will definitely update to this version and play around with those new features.
Thank you 🙏🏻

**Comment by ipatalas** [comment]
Works like a charm! Thanks again.
