### ISSUE TITLE
WithColumn With Null Propagation

### ISSUE THREAD

**Issue by lemonlion** [LightBDD/LightBDD#240]
#### Description
When using the WithColumn extension I want an easy way of doing null propagation.

For example

```
collection.ToVerifiableDataTable(b => b.WithColumn(x => x.Output.MyNullableProperty.MySubProperty));
```

In the above example when MyNullableProperty is null, I want the same behaviour as this:

```
collection.ToVerifiableDataTable(b => b.WithColumn("MySubProperty", x => x.Output.MyNullableProperty?.MySubProperty));
```

However, linq expressions do not allow inline null propogation. I was hoping the library could catch some null reference exceptions at the appropriate level to account for it.

#### Progress

- [ ] Feature is implemented,
- [ ] Ensured backward-compatibility,
- [ ] Ensured good debugging experience

**Comment by Suremaker** [comment]
Hi @lemonlion ,

Unfortunately, c# still does not allow using null propagating operators in lambda expression trees.

I really cannot implement the handling of null reference exceptions here and treat them as null values, because such logic may cover unintended behaviors/bugs.

There is a way however to overcome this limitation by wrapping either your `x.Output.MyNullableProperty?.MySubProperty` expression in a method and calling it instead in the step, or by wrapping the whole configuration of the verifiable data table columns in such method.

The example below visualizes this:

```c#
[Scenario]
public void Retrieving_contacts()
{
    var contacts = new[]
    {
        new ContactAddress("Joey",
            new Contact("Joe Jonnes", "666777888", "joe67@email.com"),
            new PostalAddress("UK", "London", "AB1 2CD", "47 Main Street")),
        new ContactAddress("Janek",
            new Contact("Jan Nowak", "123654789", "nowak33@email.com"),
            new PostalAddress("Poland", "Kraków", "31-042", "Rynek Główny 1")),
        new ContactAddress("Anonymous",new Contact("Bob",null,null),null)
    };

    Runner.RunScenario(
        _ => Given_an_address_book_with_contacts(contacts),
        _ => When_I_read_them_all(),
        // VerifiableDataTable is configured by ConfigureExpectationTable method
        _ => Then_result_should_match_expectation(contacts.ToVerifiableDataTable(ConfigureExpectationTable))
        );
}

void ConfigureExpectationTable(IVerifiableDataTableBuilder<ContactAddress> builder)
{
    // null propagating operator is allowed here
    builder
        .WithColumn("name", x => x.Contact?.Name)
        .WithColumn("city", x => x.Address?.City);
}
```
Example results:
![image](https://github.com/LightBDD/LightBDD/assets/1894621/819cd6d8-cdc4-42f8-a780-7bb604d4c4f1)
