### ISSUE TITLE
Unable to print diagnostic messages in Xunit2 SetUp/Configure

### ISSUE THREAD

**Issue by jlarke-bunnings** [LightBDD/LightBDD#252]
#### Description
Currently the only place for customisation in LightBDD.Xunit2 is through the `LightBddScopeAttribute`, which exposes two virtual methods: `OnSetup()` and `OnConfigure(LightBddConfiguration configuration)`.

I am using this to setup some DI configuration, however it's very frustrating that there is no way to access the Xunit `IMessageSink` from these methods to print one-time diagnostic methods at setup time.

Would it be possible to simply pass the `IMessageSink` through to `LightBddScopeAttribute.SetUp()` and make it available in both of the child methods?

The context for the call is here:
https://github.com/LightBDD/LightBDD/blob/ca7ccb06fef9d1fa96583c1e8db572dab915f4d3/src/LightBDD.XUnit2/Implementation/Customization/TestFrameworkExecutor.cs#L31

You can see that the `IMessageSink` is available, but currently inaccessible. Happy to put through a PR.

EDIT: Probably a separate issue, but marking every class at the Integration layer as `internal` has made it extremely difficult to extend LightBDD.XUnit2 to work with other Xunit frameworks (i.e. [Xunit.DependencyInjection](https://github.com/pengweiqhca/Xunit.DependencyInjection)). 

Is there really an issue with marking the classes `public`? Because Xunit only allows a single `TestFramework` to be defined, the only way to integrate the two libraries would be to create a parent layer that merges the behaviour of both. However LightBDD.XUnit2 doesn't expose any of its classes (unlike Xunit.DependencyInjection), meaning everything has to be copy and pasted instead, so to change out the behaviour of a couple of classes now becomes essentially a hard fork.

#### Progress

- [ ] Ensured backward-compatibility,
- [ ] Feature is implemented,
- [ ] Ensured good debugging experience

**Comment by Suremaker** [comment]
Hello @jlarke-bunnings ,

Thanks for raising this. There should not be much of an issue with exposing IMessageSink in LightBddScopeAttribute.
I will look over the weekend on how to provide it in backward compatible manner.

Regarding the second problem I would need to take a closer look on it before providing further comments. By principle the integration between LightBDD and XUnit is an implementation detail and it is internal to give freedom of reworking it when needed without the worry of impacting LightBDD users. I will come back with more thoughts on it after the weekend.

**Comment by jlarke-bunnings** [comment]
Hi @Suremaker, thanks for getting back to me. I do understand the idea behind keeping the implementation details somewhat undocumented. Unfortunately xUnit in particular is a pain because of how much of its Framework you need to override to substitute in your own code.

For example, LightBDD needs to put in its own Type Discoverer -> Assembly Runner -> Collection Runner -> Class Runner -> Method Runner -> TestCaseRunners to change some small parts of the default behaviour (i.e. parallelization).

As soon as you try and bring in another library that builds on top of xUnit (i.e [Xunit.DependencyInjection](https://github.com/pengweiqhca/Xunit.DependencyInjection)), it will try and do the exact same thing, meaning you can't get both libraries to work in tandem.

The normal approach I'd take with this is to combine the pieces of each framework (i.e. the Scenario Test Runners from LightBDD and the Dependency Injection components from Xunit.DependencyInjection) into something that enables both to work in harmony. Unfortunately with LightBDD, the entire xUnit implementation is `internal` which makes it difficult to re-use any of it.

I ended up getting it to work, but I had to use more Reflection than I would have liked.

One example is just getting LightBDD to register it's xUnit Feature Provider:

```cs
/// <summary>
/// Internal derivation of the LightBddScopeAttribute to un-protect
/// two core 'internal' functions required to ensure LightBDD scenarios
/// can function properly.
/// </summary>
/// <remarks>This is a hack, but the lightest possible touch into the LightBDD internals to get everything else to work</remarks>
internal class InternalLightBddScopeAttribute : LightBddScopeAttribute
{
    private static readonly Type CoreType = typeof(LightBddScopeAttribute);

    public void SetUp()
    {
        CoreType.GetMethod(nameof(SetUp), System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Instance)
            .Invoke(this, null);
    }

    public void TearDown()
    {
        CoreType.GetMethod(nameof(TearDown), System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Instance)
            .Invoke(this, null);
    }
}
```

**Comment by Suremaker** [comment]
Hey @jlarke-bunnings ,

With regards to the original request, I have exposed `LightBddScopeAttribute.DiagnosticMessageSink` property which can be used from `OnSetup()`/`OnConfigure()`/`OnTearDown()` methods.

Example usage can be found here: https://github.com/LightBDD/LightBDD/blob/master/test/LightBDD.XUnit2.IntegrationTests/Helpers/ConfiguredLightBDDScope.cs#L24

----

With regards to your second request, I have peeked at [Xunit.DependencyInjection](https://github.com/pengweiqhca/Xunit.DependencyInjection) project. 
The [/Xunit.DependencyInjection](https://github.com/pengweiqhca/Xunit.DependencyInjection/tree/main/Xunit.DependencyInjection) folder shows that the author has re-implemented a several xunit classes to wire up their DI solution. Similarly, LightBDD has a set of customised types which are necessary to wire up the project and provide LightBDD specific functionalities.

Unfortunately, the xunit authors did not make it easy to extend only specific parts of the integration and customise it in the additive manner.
If I expose the internals of the LightBDD (as you are asking), it would lead to following consequences:
* you would still need to choose one library classes as a base and then cherry pick parts from the second to get it wired in, which would lead to copying a lot of code,
* if you just instantiate the `LightBddScope` and call `SetUp()`/`TearDown()` methods without porting out other integration modifications (as in your example), a set of LightBDD features won't be functional or will cause issues (test ignoring, `[Scenario]` attribute, parallel test execution, just to name few),
* the exposed classes would become a part of LightBDD public interface, which would mean that I won't be able to change it easily between the versions, while it would be very easy to break the integration by incorrectly wiring up the xunit internals.

Because of the above I won't make these classes public.

I am happy however to help you overcoming the specific integration issues you are facing and potentially implementing the improvements if there are any specific gaps in the current solution.

If you are keen to use the DI for example, LightBDD already offers a support for it: https://github.com/LightBDD/LightBDD/wiki/DI-Containers (however you might need to use either [contextual scenarios](https://github.com/LightBDD/LightBDD/wiki/DI-Containers#using-di-containers-in-contextual-scenarios) or [programmatic dependency resolution](https://github.com/LightBDD/LightBDD/wiki/DI-Containers#programmatic-access-to-di-container) as the constructor injection for test classes is not supported).

Hope it helps.

**Comment by jlarke-bunnings** [comment]
@Suremaker Thanks for the reply.

So from my understanding (and I've only been in this space for a short time so I may be wrong here) there are two main components to xUnit testing:

1) Test Discovery (TestCase creation)
2) Test Execution (TestCase execution)

From what I have seen, LightBDD touches the Test Discovery phase to generate ScenarioTestCases (and ScenarioMultiTestCases for Theories) by registering an `XunitTestCaseDiscoverer`. There is a fair bit of custom code in this phase to get all of this working nicely (including custom skip handling).

On the other hand, LightBDD's footprint in the Test Execution phase is a lot lighter. From what I have been able to see, the majority of the customisation is just to set up LightBDD (via SetUp/TearDown) and to add support for `ShallEnableInterClassParallelization`. If parallelization is turned off it just defers over to the default `XunitTestAssemblyRunner` for the rest of the stack.

In contrast to this, `Xunit.DependencyInjection` has virtually no footprint in the Test Discovery phase, and does all of its work in Test Execution. 

This made integration of the two actually fairly straightforward; use Xunit.DependencyInjection for Test Execution and leave the LightBDD Test Discovery in place. The only actual code required was to use reflection to call `LightBddScopeAttribute.SetUp` and `LightBddScopeAttribute.TearDown`.

Obviously this approach loses out on the experimental test parallelization support in exchange for dependency injection, but everything else has worked fine so far.

As far as using LightBDD's in-built DI, it's unfortunately not really an option for my use case. LightBDD is just one of the BDD frameworks we use (others like BDDfy as well) so we needed something at the xUnit-level, with adapters for the various sub-frameworks. The lack of constructor injection also makes it a bit cumbersome as well.

To summarize the list of LightBDD components I had to use reflection for (just for your information):

```cs
LightBddScope:
    SetUp()
    TearDown()

ScenarioMultiTestCaseRunner:
   type definition only, to implement a custom [IXunitTestCaseRunnerAdapter)(https://github.com/pengweiqhca/Xunit.DependencyInjection/blob/main/Xunit.DependencyInjection/IXunitTestCaseRunnerAdapter.cs) that adapts it.

ScenarioTestRunner:
    ctor(...) // create the test runners from the custom adapter (since we have replaced ScenarioMultiTestCaseRunner)
    RunScenarioAsync()
```

I will try upload a proof-of-concept repo of the integration later today if I get time.

Again thanks for taking the time to read through my suggestions. I'd love it if some of these internals were made public (while remaining in an 'internal' namespace), but if you choose to leave them `internal` then I can respect that. At the end of the day all of the reflection will be contained behind a library API and I can just maintain that internally.

**Comment by jlarke-bunnings** [comment]
Update: ended up building my own framework heavily inspired by the work in Xunit.DependencyInjection:
https://github.com/declspec/XunitHostFramework

The LightBDD bindings can be found here: https://github.com/declspec/XunitHostFramework/tree/master/src/XunitHostFramework.LightBDD

**Comment by Suremaker** [comment]
Thanks @jlarke-bunnings for sharing the details.

For next major version I will be reviewing the integrations with test frameworks and the way how DI is supported for LightBDD. I will reconsider then on how LightBDD integrates with xunit.
