### ISSUE TITLE
Really unclear how to update 1.x to 2.x

### ISSUE THREAD

**Issue by togakangaroo** [LightBDD/LightBDD#26]
I'm trying to upgrade my project right now and am very confused. I've read [this article on the wiki](https://github.com/LightBDD/LightBDD/wiki/Migrating-LightBDD-Versions) but it seems to offer little by way of explanation or examples.

My big confusion is what happened to the old `Runner` property. I note that we no longer use the `FeatureFixture` base class, but are now using partial classes but I see no mention of what the other "side" of the partial is supposed to be, nor any mention of this in the doc.

Also, there seems to not be a `Scenario` attribute...

**Comment by Suremaker** [comment]
Hello,

I have not put much about the `Runner` property nor partial classes because not much has changed in this area. Both version 1x and 2x were suggesting to use partial class and derive from `[FeatureFixture]` attribute.

Just for the comparison, please take a look at the example projects:
* [LightBDD 1.x examples for NUnit3 integration](https://github.com/LightBDD/LightBDD/tree/1.x/LightBDD.Example.AcceptanceTests.NUnit3)
* [LightBDD 2.x examples for NUnit3 integration](https://github.com/LightBDD/LightBDD/tree/master/examples/LightBDD.Example.AcceptanceTests.NUnit3)

In LightBDD 2, the sample test class looks like that:

Scenario part:
```c#
using LightBDD.Framework;
using LightBDD.Framework.Scenarios.Basic;
using LightBDD.NUnit3;

namespace LightBDD.Example.AcceptanceTests.NUnit3.Features
{
    [FeatureDescription(
@"In order to access personal data
As an user
I want to login into system")]
    [Label("Story-1")]
    public partial class Login_feature
    {
        [Scenario]
        [Label("Ticket-1")]
        [ScenarioCategory(Categories.Security)]
        public void Successful_login()
        {
            Runner.RunScenario(

                Given_the_user_is_about_to_login,
                Given_the_user_entered_valid_login,
                Given_the_user_entered_valid_password,
                When_the_user_clicks_login_button,
                Then_the_login_operation_should_be_successful,
                Then_a_welcome_message_containing_user_name_should_be_returned);
        }
        /* ... */
}
```

Steps part: 
```c#
using LightBDD.Example.Services;
using LightBDD.Framework;
using LightBDD.Framework.Commenting;
using LightBDD.NUnit3;
using NUnit.Framework;

namespace LightBDD.Example.AcceptanceTests.NUnit3.Features
{
    public partial class Login_feature : FeatureFixture
    {
        private const string _validUserName = "admin";
        private const string _validPassword = "password";

        private LoginRequest _loginRequest;
        private LoginService _loginService;
        private LoginResult _loginResult;

        private void Given_the_user_is_about_to_login()
        {
            _loginService = new LoginService();
            _loginService.AddUser(_validUserName, _validPassword);
            _loginRequest = new LoginRequest();
        }

        private void Given_the_user_entered_valid_login()
        {
            _loginRequest.UserName = _validUserName;
        }
        /* ... */
}
```

As you can see, the fixture still inherits from `FeatureFixture` to obtain the `Runner` property.
What is different is that:
* `[Test]` has been changed to `[Scenario]`
* `RunScenario*()` methods are extension methods now so you have to use the namespace of the method you like - the above example uses basic syntax, so it uses: `using LightBDD.Framework.Scenarios.Basic;`
* on the assembly level, you have to initialize the LightBDDScope by stating `[assembly: LightBddScope]` - this is also the place where you can configure LightBDD now (see [wiki page on configuration](https://github.com/LightBDD/LightBDD/wiki/LightBDD-Configuration))


> Also, there seems to not be a `Scenario` attribute...

This thing is interesting for me and suggests that maybe you have some missing package references or mixture of 1.x and 2.x package versions in the project ?

Please ensure that you have:
* LightBDD.Core, LightBDD.Framework and LightBDD.NUnit3 packages of version 2.X in your project (of course if you use something else than NUnit3, then replace it with appropriate package equivalent).

Finally, there are example projects mentioned at the bottom of the wiki page you linked in question.
They shows example usage of basic, extended syntax, contexts as well as async usages for all test frameworks LightBDD suports - feel free to explore them: https://github.com/LightBDD/LightBDD/tree/master/examples

Please let me know if you still have any issues with migration, or if the response helped you.

**Comment by togakangaroo** [comment]
Ok, I think I got it now. So I'd recommend modifying the migration wiki page to add in that

* `FeatureFixture` still exists, its just moved into the `LightBdd.Nunit3` package (which didn't install by default when I did `Update-Package LightBdd.NUnit`)
* That you should uninstall old `LightBdd.NUnit` packages

**Comment by Suremaker** [comment]
Thanks for the feedback. I'll definitely update the migration page.

**Comment by Suremaker** [comment]
I have added Migration process in a nutshell section: https://github.com/LightBDD/LightBDD/wiki/Migrating-LightBDD-Versions#migration-process-in-a-nutshell

Please let me know if it is clear and contains all information that is needed
