### ISSUE TITLE
How can you enforce specific steps to run if the scenario fails in previous steps

### ISSUE THREAD

**Issue by EdwardBrincat** [LightBDD/LightBDD#280]
#### Description
I would like to know whether there is a way to enforce specific steps to execute even if the scenario fails before it reaches these steps. Like in the case of a try, catch and finally statement where the code within the finally section always executes.

#### Progress

- [ ] Feature is implemented,
- [ ] Ensured backward-compatibility,
- [ ] Ensured good debugging experience

**Comment by Suremaker** [comment]
Hi @EdwardBrincat,

LightBDD currently does not allow you to enforce some specific steps to execute regardless of previous steps' results.

Having said that, you can use [MultiAssertAttribute](https://github.com/LightBDD/LightBDD/wiki/Tests-Structure-and-Conventions#multiassertattribute) on the scenario, in which case all its steps will be executed regardless of their execution results. This is the example showing its usage: [code](https://github.com/LightBDD/LightBDD/blob/master/examples/Example.LightBDD.XUnit2/Features/Calculator_feature.cs#L29) and the corresponding results: [Html Result](https://htmlpreview.github.io/?https://github.com/LightBDD/LightBDD/blob/master/examples/ExampleReports/FeaturesReport.html#feature3)

Alternatively, if you are looking for executing some kind of initialization-cleanup code, you can use the [decorators](https://github.com/LightBDD/LightBDD/wiki/Extending-Test-Behavior) which you can apply to entire scenarios or the specific steps. 

Please let me know if any of these features are helpful for you. Alternatively, please feel free to describe what exactly you are trying to achieve - perhaps I would be able to suggest some solution.

**Comment by Suremaker** [comment]
Hello @EdwardBrincat ,

With LightBDD 3.7.0 it is possible now to use `IScenarioTearDown` interface on the feature fixture to implement the asynchronous `OnScenarioTearDown()` method to run an additional cleanup.
The documentation of this feature is here: [Scenario SetUp and TearDown](https://github.com/LightBDD/LightBDD/wiki/SetUp-and-TearDown#scenario-setup-and-teardown).
This is one more alternative to the ones provided above.

As I did not hear from you since last time, I presume your question is answered.
