### ISSUE TITLE
Question: Is it possible to scope Global Setup\Teardown to a namespace

### ISSUE THREAD

**Issue by DizzyDeveloper** [LightBDD/LightBDD#335]
#### Description

Is it possible to scope global setup and teardown operations to a namespace? Similar to how NUnit OneTimeSetUp and OneTimeTearDown can be scoped. Such that those setup and teardown operations only run when tests at the same namespace level (or below) are run?
I have a scenario at the moment where I have two groups of tests, each group needs some pre-emptive configurations run. However, those pre-emptive steps can be heavy, and I don't want to run global setups for both groups of tests when I only want to run one group of tests.

**Comment by Suremaker** [comment]
Hello @DizzyDeveloper,

Currently, LightBDD does not offer convention nor attribute driven setup/teardown methods similar to mentioned NUnit functionality.

Having said that, there are few options that can be considered:
1. If you use LightBDD for NUnit, you can just use mentioned nunit methods - LightBDD is just run on top of the nunit in this case.
2. You can use [ScenarioDecorator](https://github.com/LightBDD/LightBDD/wiki/Extending-Test-Behavior#scenario-decorators). It will be run for each decorated scenario where you will be able to detect first execution and run your complex setup.  
If you have only few classes within your namespace that need this setup, you can apply this decorator on the [class level](https://github.com/LightBDD/LightBDD/wiki/Extending-Test-Behavior#class-level). Alternatively you can apply it [globally](https://github.com/LightBDD/LightBDD/wiki/Extending-Test-Behavior#global-level) and use `IScenario.Fixture` to determine the namespace of currently executed class.  
If you need to run disposal/cleanup, you may be limited to run it only at the end of all test as currently there is no easy way to tell that all scenarios of given class/namespace have already executed.  
To trigger cleanup you can:
* call static cleanup method on your decorator class via [RegisterGlobalTeardown](https://github.com/LightBDD/LightBDD/wiki/SetUp-and-TearDown#registerglobalsetup)
* if you use decorator registered globally, you can add its instance to the container too via [RegisterInstance](https://github.com/LightBDD/LightBDD/wiki/DI-Containers#configuration-options) so that DI will dispose it. This won't work for decorators applied via attribute (class level) as creation of these decorators is not tied to DI and they are instantiated for each scenario.

I hope this helps. Let me know if you have any issues.

Thanks

**Comment by DizzyDeveloper** [comment]
Hi @Suremaker,

Thanks for the feedback :) I am aware that I could use the NUnit functions, I asked because I really liked the DI functionality to retrieve globally executed setups properties within steps, rather than having to access static properties on the class; its quiet neat :)

I will have a further look into the scenario decorators for now.

Thanks again
