### ISSUE TITLE
NUnit3. Tests with ignore annotation doesn't appear in html report

### ISSUE THREAD

**Issue by APshenkin** [LightBDD/LightBDD#41]
Here is an example of test:
```
        [Ignore("false positive")]
        [Scenario]
        public void test(string version)
        {
            lat = Config.GetConfig ().testCities.msk.lat;
            lng = Config.GetConfig ().testCities.msk.lng;
            cinemaId = Config.GetConfig ().testCinemas.additionalgoodsCinema.id;
            
            Runner.RunScenario(
                _ => Given_api_version(version),
                _ => Given_lat_and_lng(lat, lng),
                _ => When_we_trying_post_order_to_3D_movie(cinemaId),
                _ => Then_we_get_statusCode_OK(response),
        }
```

When launch this test, in Nunit Console output this tests are marked as `ignored`
But in LightBDD output this tests doesn't appear at all

**Comment by Suremaker** [comment]
Hello,

This is an expected behavior unfortunately. The underlying test framework (NUnit in this case) controls the `[Ignore]` attribute and it skips the scenario without giving LightBDD an opportunity to execute the scenario.

If you would like to see the scenario appearing in LightBDD report, please use `Assert.Ignore()` in one of the step executed by the scenario instead.

The scenario ignoring behavior is described [on wiki](https://github.com/LightBDD/LightBDD/wiki/Tests-Structure-and-Conventions#conventions) and there is an example code [here](https://github.com/LightBDD/LightBDD/blob/master/examples/LightBDD.Example.AcceptanceTests.NUnit3/Features/Basket_feature.Steps.cs#L56) with report [here](http://htmlpreview.github.io/?https://github.com/LightBDD/LightBDD/blob/master/examples/ExampleReports/FeaturesReport.html?cat=-all-#scenario1_2).

I have updated that wiki page section with a note that `[Ignore]` attribute behavior.

**Comment by Suremaker** [comment]
On second thought I identified some use cases where an ability to mark scenario with ignore attribute would be useful. While I don't think it would be possible to change the behavior of `[Ignore]` attribute without significant interference in the test framework, I could provide unified, LightBDD specific `[ScenarioIgnore]` attribute that would ignore the scenario in a way that it would appear in the report.

In the time being, I would suggest to use the `Assert.Ignore()` method described above.

**Comment by APshenkin** [comment]
@Suremaker Thanks a lot for the answer! Will use workaround with custom step with `Assert.Ignore()` and will wait for `[ScenarioIgnore]`!
