### ISSUE TITLE
Supported .Net Framework versions

### ISSUE THREAD

**Issue by ssg47** [LightBDD/LightBDD#71]
In your documentation on [ReadMe.md](https://github.com/LightBDD/LightBDD/blob/master/README.md) and [Test Framework Integrations](https://github.com/LightBDD/LightBDD/wiki/Test-Framework-Integrations) you refer to supporting .NET Framework 4.5 but in the examples, in LightBDD.Example.AcceptanceTests.NUnit2.csproj, I noticed 

`<ItemGroup Condition=" '$(TargetFramework)' == 'net46' ">`

Does LightBDD now support .NET Framework 4.6?

**Comment by Suremaker** [comment]
Hello, yes the LightBDD.NUnit2 supports net45: https://github.com/LightBDD/LightBDD/blob/master/src/LightBDD.NUnit2/LightBDD.NUnit2.csproj#L12
And it do generate package for net45: https://www.nuget.org/packages/LightBDD.NUnit2/

It is a good spot that tests for it are referring to net46 (when I come back I'll check the reason as it may be omission).

**Comment by Suremaker** [comment]
All the framework functionality (tests for LightBDD.Core and Framework) are tested against .net451 and it is definitely safe to use that version.
The .net 45(0) is definitely supported as well by LightBDD (I am using 451 in tests because of some new api that makes tests easier to write I believe - I'll check it after coming back what it was exactly).

I hope it helps.

**Comment by ssg47** [comment]
Thanks for the update.  

Do you have an idea of when you'll support 4.6.2 or even 4.7?

**Comment by Suremaker** [comment]
The net45 is a minimal supported version. It works out of the box with all the newer net versions, so feel free to pick any you like :)
The LightBDD.NUnit3 works also with Net Core

**Comment by ssg47** [comment]
Thank you for the clarification.
